### ISSUE TITLE
Montar la Base de Datos

### ISSUE THREAD

**Issue by CDisidoro** [CDisidoro/Practica2-AW#1]
En este capítulo se debe detallar la estructura de la base de datos, indicando las tablas,
campos y relaciones. También se puede incluir un diagrama entidad-relación.
Para cada tabla se debe indicar su propósito, detallar los scripts que acceden a la tabla
(indicando si sólo consultan o también modifican) y explicar los campos que contiene.
Las explicaciones se pueden acompañar de diagramas en formatos adecuados para
representar la estructura (por ejemplo, pero no necesariamente, diagramas de entidad-relación)

**Comment by CDisidoro** [comment]
USUARIOS:
- ID
- Nombre de Usuario (Irrepetible)
- Contraseña
- Correo Electronico
- Lista de Amigos (Many To Many con tabla Aux)
- Rol (Solo uno por usuario)
- Biografía
- Avatar (Numero de imagen predefinida entre X opciones)
- Bandeja de Entrada de solicitudes de amistad 
- Lista de Juegos (Vacía de momento)

**Comment by Dav16d** [comment]
Código primario para los usuarios que se moderen en la base de datos así como el establecimiento de las rutas y parámetros claves para la utilización de la aplicación web y gestión principal de registro de los usuarios.

**Cosas que faltan por definir:** @CDisidoro 

- [ ]  Fotos necesarias tales como usuario default, admin o escritor

- [ ]  Establecer getters de descripcion y fotos por defecto

- [ ]  Incluir información referente a la descripción y recogida de su funcionalidad

- [ ] A su vez actualmente solo está creada la tabla de contenido principal (bd Gamers Deen), creo que faltarían las tablas de las bases de datos cuando se vayan rellenando

**Comment by CDisidoro** [comment]
> 

- Sobre las fotos, está cargado por defecto para todos los usuarios que le cargue una imagen con numero 1 (Que seria la generica foto gris) por defecto. Si tenemos que ponerle fotos específicas al admin o al escritor cuando se cree su cuenta, en la query que cree ese usuario se le especifica un número de foto reservado para el escritor y el administrador
- Que es lo de getters de descripción y fotos por defecto?
- De la descripción supongo que te refieres a la "biografía" del usuario, pero donde debo incluir esa información referente a la bio?
- Y de las otras tablas para la BD tengo pensada de momento una tabla de juegos donde se añadan los juegos que tendrá la página, pero qué otras tablas vamos a meter? Si tenéis ideas de otras tablas y que podrían tener avisarme

**Comment by CDisidoro** [comment]
Ya he creado en principio la BD y la he documentado en la memoria. Si hay algo que modificar o mejorar avisarme. Cierro el Issue
